services:
  web:
    build:
      context: .
    volumes:
      - ./space_app:/space_app
      - media:/space_app/mediafiles
      - static:/space_app/staticfiles
    env_file:
      - ./space_app/.env
    expose:
      - 8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn -w 5 -b 0.0.0.0:8000 space_app.wsgi"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./space_app/.env

  redis:
    image: redis:7.0.5
    hostname: redis

  celery:
    build:
      context: .
    command: celery -A space_app worker -l info
    volumes:
      - ./space_app:/space_app
    env_file:
      - ./space_app/.env
    links:
      - redis
    depends_on:
      - redis
      - database

  celery-beat:
    build:
      context: .
    command: celery -A space_app beat -l
    volumes:
      - ./space_app:/space_app
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - ./space_app/.env

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - media:/space_app/mediafiles
      - static:/space_app/staticfiles
    depends_on:
      - web

volumes:
  postgres-data:
  static:
  media: